name:                mangrove
version:             0.0.0.0
github:              "hstream-io/mangrove"
license:             BSD3
author:              Commelina
maintainer:          "maosics@gmail.com"
copyright:           "2020 EMQ Technologies Co., Ltd."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hstream-io/mangrove#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- time
- text
- containers
- vector
- exceptions
- mtl
- conduit
- transformers
- network
- network-simple
- optparse-applicative
- hesp
- log-store
- co-log

library:
  source-dirs: src

executables:
  mangrove-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mangrove

tests:
  mangrove-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - mangrove
    - temporary
