resolver: lts-15.13

packages:
  - .

extra-deps:
  - git: https://github.com/hstream-io/log-store
    commit: 1e427d354847273b637266936fda2e69ee415e45
  - git: https://github.com/hstream-io/haskell-rocksdb-bindings
    commit: e62ed5d0f4d9eedd56ae01c49185a06465ba3eb3

  - git: https://github.com/hstream-io/hesp.git
    commit: c817b86aec651e3e1dfcda33e8e7220e94e29033
