# Host that the server listening on
host: 0.0.0.0

# Port that the server listening on
port: 6560

# Path to the database on the disk
db-path: /tmp/db-test

logger:
  formatter: rich   # rich or simple
  level: info
