# Host that the server listening on
host: 0.0.0.0

# Port that the server listening on
port: 6560

database:
  # Path to the database on the disk
  path: /tmp/db-test
  # Size of column family write buffer, in bytes.
  # Recommended value is 1/3 of max memory
  write-buffer-size: 314572800    # 300 * 1024 * 1024
  # DB statistics
  enable-stats: false
  # DB statistics dump period, in seconds
  stats-period: 10

logger:
  formatter: rich   # rich or simple
  level: info
