# Host that the server listening on
host: localhost

# Port that the server listening on
port: 20202

# Path to the database on the disk
db-path: /tmp/db-test

logger:
  formatter: rich   # rich or simple
  level: info
