# Host that the server listening on
host: 0.0.0.0

# Port that the server listening on
port: 6560

# Path to the database on the disk
db-path: /tmp/db-test

# Size of column family write buffer, in bytes, default is 300M
cfWriteBufferSize: 314572800    # 300 * 1024 * 1024

# Size of DB write buffer, in bytes
dbWriteBufferSize: 0

# DB statistics
enableDBStats: true

# DB statistics dump period, in seconds
dbStatsPeriodSec: 10

logger:
  formatter: rich   # rich or simple
  level: info
