name: Build and Run tests

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

env:
  IMAGE: hstreamio/haskell-rocksdb

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    name: Get matrixes
    outputs:
      ghc: ${{ steps.parser.outputs.ghc }}
    steps:
      - uses: actions/checkout@v2
      - id: parser
        run: >
          echo "::set-output name=ghc::$(
          cat mangrove.cabal | grep tested-with |
          sed -e 's/[^0-9|\.]/ /g' -e 's/^ *//g' -e 's/ *$//g' |
          python3 -c 'import sys, json; print(json.dumps([x.strip() for x in sys.stdin.read().split()]))'
          )"

  build:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ${{fromJson(needs.set-matrix.outputs.ghc)}}

    name: GHC-${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}

      - name: Pull ghc-${{ matrix.ghc }} image and start build-${{ matrix.ghc }} container.
        run: |
          docker pull $IMAGE:${{ matrix.ghc }}
          docker run -td --rm --name build-${{ matrix.ghc }} -v $HOME/.cabal:/root/.cabal -v $(pwd):/srv -w /srv $IMAGE:${{ matrix.ghc }} bash

      - name: Install dependencies
        run: |
          docker exec build-${{ matrix.ghc }} cabal update
          docker exec build-${{ matrix.ghc }} cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Build
        run: docker exec build-${{ matrix.ghc }} cabal build --enable-tests --enable-benchmarks all

      - name: Run tests
        run: docker exec build-${{ matrix.ghc }} cabal test all

      - name: Run cabal check
        run: docker exec build-${{ matrix.ghc }} cabal -vnormal check

      - name: Haddock
        run: docker exec build-${{ matrix.ghc }} cabal haddock --enable-tests --enable-benchmarks all
